spring:
  profiles:
    active: local
    include:
      - domain
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            admin-key: ${KAKAO_ADMIN_KEY}
    auth:
      jwt:
        secret-key: ${JWT_SECRET_KEY}
        access-exp: ${JWT_ACCESS_EXP}
        refresh-exp: ${JWT_REFRESH_EXP}
---
spring:
  config:
    activate:
      on-profile: local
logging:
  level:
    com.example.enterparkticket.apis.* : debug
---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    com.example.enterparkticket.apis.* : debug
---
spring:
  config:
    activate:
      on-profile: prod
