spring:
  profiles:
    active: local
    include:
      - domain
  batch:
    job:
      name: ${job.name:NONE}
    chunk-size: ${CHUNK_SIZE:1000}
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
